### PR TITLE
Fix wrong Ruby versions in .travis.yml.

### PR DESCRIPTION
**Pull request by junaruga**
This PR fixes issue by https://github.com/rails/coffee-rails/pull/98.
Let me try to run and see the result on Travis CI at first.

### CODE REVIEW

**Comment by junaruga** [comment]
https://travis-ci.org/rails/coffee-rails/builds/394045850

### JRuby + gemfiles/Gemfile-4-0-stable

```
/home/travis/.rvm/rubies/jruby-9.0.5.0/lib/ruby/stdlib/minitest.rb:46: warning: (...) interpreted as grouped expression
MiniTest::Unit.autorun is now Minitest.autorun. From /home/travis/build/rails/coffee-rails/gemfiles/vendor/bundle/jruby/2.2.0/bundler/gems/rails-9be9597e510d/activesupport/lib/active_support/testing/autorun.rb:5:in `<top>'
NameError: undefined method '_run_suites' for class 'Minitest::Unit'
```
It seems that stdlib's minitest is called instead of separately installed minitest.

### Ruby 2.2, 2.3 + Gemfile

```
Resolving dependencies....
activesupport-6.0.0.alpha requires ruby version >= 2.4.1, which is incompatible
```

Do you like removing this test cases?

**Comment by rafaelfranca** [comment]
> Do you like removing these test cases?

Yes

**Comment by junaruga** [comment]
Ok, I will remove those test cases tomorrow. Just moment.

**Comment by junaruga** [comment]
@rafaelfranca ping

**Comment by rafaelfranca** [comment]
Let's put a requirement to rake for now.

**Comment by junaruga** [comment]
@rafaelfranca done. merge please.

**Pull request merged**
